#!/bin/bash
  
MYSQL=`which mysql`
  
Q1="DROP DATABASE alpheus;"
Q2="CREATE DATABASE alpheus character set utf8;;"
SQL="${Q1}${Q2}"

$MYSQL -uroot -pasdf --database alpheus -e "$SQL"
python manage.py syncdb --noinput
